# Generated by Django 4.1.3 on 2022-11-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.TextField()),
                ('short', models.TextField()),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'main',
            },
        ),
    ]
